### PR TITLE
Allow exit with ctrl+c

### PR DESCRIPTION
**Pull request by MoHermes**
On connection setup, keyboard interrupt should be caught to gracefully quit .

### CODE REVIEW

**Review by hJaffaliColibritd — CHANGES_REQUESTED** [review]
Tested the script while checking out this branch, but nothing happens when I press Ctrl+C while being in the main menu, Neither any other key combination. Tested on a windows console. Works fine when I select a choice of configuration (ibm, aws, ...)

image

**Comment by hJaffaliColibritd** [comment]
image

On Linux console (Docker image with the current code), KeyboardInterrupt catched but raised apparently

**Comment by henridb** [comment]
> Tested the script while checking out this branch, but nothing happens when I press Ctrl+C while being in the main menu, Neither any other key combination. Tested on a windows console. Works fine when I select a choice of configuration (ibm, aws, ...)

to put more precise words on the problem: we could call the two modes described the `pick` mode (when we use the library of the same name to pick a choice), and the `I/O` mode (when we are in the terminal display/input mode). So the problem you're describing is that the `pick` mode seems to capture the `KeyboardInterrupt` and stops it from having the usual effect (quitting the program).

**Comment by Henri-ColibrITD** [comment]
> Tested the script while checking out this branch, but nothing happens when I press Ctrl+C while being in the main menu, Neither any other key combination. Tested on a windows console. Works fine when I select a choice of configuration (ibm, aws, ...)

to put more precise words on the problem: we could call the two modes described the `pick` mode (when we use the library of the same name to pick a choice), and the `I/O` mode (when we are in the terminal display/input mode). 

So the problem you're describing is that the `pick` mode seems to capture the `KeyboardInterrupt` and stops it from having the usual effect (quitting the program).

**Comment by Henri-ColibrITD** [comment]
> Tested the script while checking out this branch, but nothing happens when I press Ctrl+C while being in the main menu, Neither any other key combination. Tested on a windows console. Works fine when I select a choice of configuration (ibm, aws, ...)

I confirm that this problem arises on my machine too

**Review by Henri-ColibrITD — CHANGES_REQUESTED** [review]
feature not working

**Comment by hJaffaliColibritd** [comment]
> Another problem @hJaffaliColibritd described (although for some reason I don't see it in this feed) is that the `I/O` mode doesn't exit gracefully on Linux (tested on a docker container)

I checked back on docker and Linux, it works, so I removed my comment in this PR

**Review by Henri-ColibrITD — APPROVED** [review]
looks good to me now

**Review by hJaffaliColibritd — APPROVED** [review]

**Pull request merged**
